# Generated by Django 5.2.14 on 2026-05-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='description',
            field=models.TextField(help_text='Job description in Markdown (README-style).'),
        ),
    ]
