# Generated by Django 5.2.14 on 2026-05-31 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='applications.application'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='recommendation',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
